vim.g.mapleader = " "

vim.keymap.set("i", "jk", "<ESC>", { desc = "Exit insert mode with jk" })
vim.keymap.set("n", "<leader>nh", ":nohl<CR>", { desc = "Clear search highlights" })
vim.keymap.set("n", "<leader>+", "<C-a>", { desc = "Increment number" })
vim.keymap.set("n", "<leader>-", "<C-x>", { desc = "Decrement number" })

vim.keymap.set({ "n", "x" }, "p", "<Plug>(YankyPutAfter)")
vim.keymap.set({ "n", "x" }, "P", "<Plug>(YankyPutBefore)")
vim.keymap.set({ "n", "x" }, "gp", "<Plug>(YankyGPutAfter)")
vim.keymap.set({ "n", "x" }, "gP", "<Plug>(YankyGPutBefore)")

vim.keymap.set("n", "<c-n>", "<Plug>(YankyPreviousEntry)")
vim.keymap.set("n", "<c-p>", "<Plug>(YankyNextEntry)")

vim.keymap.set("n", "lg", ":LazyGit<CR>", { desc = "LazyGit" })
vim.keymap.set("n", "<leader>ee", ":NvimTreeToggle<CR>", { desc = "Nvim Tree toggle" })

vim.keymap.set("n", "s", require("substitute").operator, { noremap = true })
vim.keymap.set("n", "ss", require("substitute").line, { noremap = true })
vim.keymap.set("n", "S", require("substitute").eol, { noremap = true })
vim.keymap.set("x", "s", require("substitute").visual, { noremap = true })

local harpoon_mark = require("harpoon.mark")
vim.keymap.set("n", "<leader>fa", harpoon_mark.add_file, { desc = "Add file to Harpoon" })

local harpoon_ui = require("harpoon.ui")
vim.keymap.set("n", "<leader>f1", function()
	harpoon_ui.nav_file(1)
end, { desc = "Navigate to Harpoon file 1" })
vim.keymap.set("n", "<leader>f2", function()
	harpoon_ui.nav_file(2)
end, { desc = "Navigate to Harpoon file 2" })
vim.keymap.set("n", "<leader>f3", function()
	harpoon_ui.nav_file(3)
end, { desc = "Navigate to Harpoon file 3" })
vim.keymap.set("n", "<leader>f4", function()
	harpoon_ui.nav_file(4)
end, { desc = "Navigate to Harpoon file 4" })
vim.keymap.set("n", "<leader>f5", function()
	harpoon_ui.nav_file(5)
end, { desc = "Navigate to Harpoon file 5" })
vim.keymap.set("n", "<leader>f6", function()
	harpoon_ui.nav_file(6)
end, { desc = "Navigate to Harpoon file 6" })

vim.keymap.set("n", "<leader>fl", harpoon_ui.toggle_quick_menu, { desc = "Toggle Harpoon Menu" })
vim.keymap.set("n", "<leader>fn", harpoon_ui.nav_next, { desc = "Navigate to next Harpoon mark" })
vim.keymap.set("n", "<leader>fp", harpoon_ui.nav_prev, { desc = "Navigate to previous Harpoon mark" })

local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fr", builtin.oldfiles, { desc = "Telescope find recent files" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
